version: '3.5'

services:
  database:
    image: mysql
    container_name: duomenu-baze
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: verygoodpassword
      MYSQL_DATABASE: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql_volume: